### ISSUE TITLE
Non-required param as batchKey for batch resources would cause flow type check errors.

### ISSUE THREAD

**Issue by jwen817** [Yelp/dataloader-codegen#192]
Currently when a batch resource is configured, if the batchKey for the underlying endpoint is not a required param, there will be flow type check errors raised.

### **Issue sample with details**
---
For an endpoint like:
```
    TestUserApi:
        getUsers:
            isBatchResource: true
            docsLink: http://hostname/?service=testservice#/testuserapi/get_users
            batchKey: user_ids
            newKey: user_id
            reorderResultsByKey: id
```
where the `user_ids` param is non-required, the generated clientlib would look like:

`getUsers($ReadOnly<{| user_ids?: $ReadOnlyArray<number>, user_emails?: $ReadOnlyArray<string>,  |}>, options?: RequestOptions): Promise<Array<User>>,`

in the `lib/api.js.flow` file. Note for **user_ids** it looks like: `user_ids?: $ReadOnlyArray<number>`.

At runtime, everything works as expected, as long as the **user_ids** is supplied properly.

But when doing flow type validation, it will cause below error:

```
Cannot instantiate `$ElementType` because an index signature declaring the expected key / value type is missing in
undefined [1].

                        v------------
               user_id: $ElementType<
                 $PropertyType<
                   $Call<
                     ExtractArg,
                     [
                       $PropertyType<
                         $PropertyType<ResourcesType, "TestUserApi">,
                         "getUsers"
                       >
                     ]
                   >,
                   "user_ids"
                 >,
                 0
               >
                ^
References:
   node_modules/@test-clientlib/testapi/lib/api.js.flow:
        getUsers($ReadOnly<{| user_ids?: $ReadOnlyArray<number>, user_emails?: $ReadOnlyArray<string>,  |}>, options?: RequestOptions): Promise<Array<User>>,
                                         ^^^^^^^^^^^^^^^^^^^^^ [1]

```
